---
config:
  layout: dagre
---
flowchart LR
 subgraph s1["Usuário"]
        U1["Usuário a responder a um questionário"]
        U2["Usuário a anunciar um carro"]
  end
 subgraph APIs["APIs"]
        api1["Gmail"]
        api2["API informações dos carros"]
  end
    Adm["Administrador"] -- Gerencia denúncias --> AP["Aplicação Web"]
    AP -- Feedback de Ações de Gerenciamento --> Adm
    U1 -- Envia Respostas --> AP
    U2 -- Publica Anúncio --> AP
    api1 -- autoriza e envia os dados --> AP
    api2 -- devolve descrições, nomes e características --> AP
    AP -- Envia perguntas --> U1
    AP -- Confirmação / Status do Anúncio --> U2
    AP -- solicita autenticação e informações --> api1
    AP -- solicita informações --> api2
